---@diagnostic disable: missing-fields
return {
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function()
            require("nvim-treesitter.configs").setup({
                auto_install = true,
                ensure_installed = {
                },
                highlight = {
                    enable = true,
                },
                indent = {
                    enable = true,
                },
            })
        end
    },
    {
        "nvim-treesitter/nvim-treesitter-textobjects",
        dependencies = {
            "nvim-treesitter/nvim-treesitter",
        },
        config = function()
            require "nvim-treesitter.configs".setup({
                textobjects = {
                    select = {
                        enable = true,
                        include_surrounding_whitespace = false,
                        lookahead = true,
                        keymaps = {
                            ["af"] = "@function.outer",
                            ["if"] = "@function.inner",
                            ["as"] = "@class.outer",
                            ["is"] = "@class.inner",
                            ["ac"] = "@conditional.outer",
                            ["ic"] = "@conditional.inner",
                            ["al"] = "@loop.outer",
                            ["il"] = "@loop.inner",
                            ["ap"] = "@parameter.outer",
                            ["ip"] = "@parameter.inner",
                            ["ia"] = "@attribute.inner",
                            ["aa"] = "@attribute.outer",
                            ["ik"] = "@comment.inner",
                            ["ak"] = "@comment.outer",
                            ["ir"] = "@return.inner",
                            ["ar"] = "@return.outer",
                        },
                        selection_modes = {
                            ["@function.outer"] = "V",
                            ["@function.inner"] = "V",
                            ["@class.outer"] = "V",
                            ["@class.inner"] = "V",
                            ["@conditional.outer"] = "V",
                            ["@conditional.inner"] = "V",
                            ["@loop.outer"] = "V",
                            ["@loop.inner"] = "V",
                            ["@parameter.outer"] = "V",
                            ["@parameter.inner"] = "V",
                            ["@attribute.inner"] = "V",
                            ["@attribute.outer"] = "V",
                            ["@comment.inner"] = "V",
                            ["@comment.outer"] = "V",
                            ["@return.inner"] = "V",
                            ["@return.outer"] = "V",
                        },
                    },
                    move = {
                        enable = true,
                        set_jumps = true,
                        goto_next_start = {
                            ["]af"] = "@function.outer",
                            ["]if"] = "@function.inner",
                            ["]as"] = "@class.outer",
                            ["]is"] = "@class.inner",
                            ["]ac"] = "@conditional.outer",
                            ["]ic"] = "@conditional.inner",
                            ["]al"] = "@loop.outer",
                            ["]il"] = "@loop.inner",
                            ["]ap"] = "@parameter.outer",
                            ["]ip"] = "@parameter.inner",
                            ["]ia"] = "@attribute.inner",
                            ["]aa"] = "@attribute.outer",
                            ["]ik"] = "@comment.inner",
                            ["]ak"] = "@comment.outer",
                            ["]ir"] = "@return.inner",
                            ["]ar"] = "@return.outer",
                        },
                        goto_next_end = {
                            ["[af"] = "@function.outer",
                            ["[if"] = "@function.inner",
                            ["[as"] = "@class.outer",
                            ["[is"] = "@class.inner",
                            ["[ac"] = "@conditional.outer",
                            ["[ic"] = "@conditional.inner",
                            ["[al"] = "@loop.outer",
                            ["[il"] = "@loop.inner",
                            ["[ap"] = "@parameter.outer",
                            ["[ip"] = "@parameter.inner",
                            ["[ia"] = "@attribute.inner",
                            ["[aa"] = "@attribute.outer",
                            ["[ik"] = "@comment.inner",
                            ["[ak"] = "@comment.outer",
                            ["[ir"] = "@return.inner",
                            ["[ar"] = "@return.outer",
                        },
                        goto_previous_start = {
                            ["}af"] = "@function.outer",
                            ["}if"] = "@function.inner",
                            ["}as"] = "@class.outer",
                            ["}is"] = "@class.inner",
                            ["}ac"] = "@conditional.outer",
                            ["}ic"] = "@conditional.inner",
                            ["}al"] = "@loop.outer",
                            ["}il"] = "@loop.inner",
                            ["}ap"] = "@parameter.outer",
                            ["}ip"] = "@parameter.inner",
                            ["}ia"] = "@attribute.inner",
                            ["}aa"] = "@attribute.outer",
                            ["}ik"] = "@comment.inner",
                            ["}ak"] = "@comment.outer",
                            ["}ir"] = "@return.inner",
                            ["}ar"] = "@return.outer",
                        },
                        goto_previous_end = {
                            ["{af"] = "@function.outer",
                            ["{if"] = "@function.inner",
                            ["{as"] = "@class.outer",
                            ["{is"] = "@clasj.inner",
                            ["{ac"] = "@conditional.outer",
                            ["{ic"] = "@conditional.inner",
                            ["{al"] = "@loop.outer",
                            ["{il"] = "@loop.inner",
                            ["{ap"] = "@parameter.outer",
                            ["{ip"] = "@parameter.inner",
                            ["{ia"] = "@attribute.inner",
                            ["{aa"] = "@attribute.outer",
                            ["{ik"] = "@comment.inner",
                            ["{ak"] = "@comment.outer",
                            ["{ir"] = "@return.inner",
                            ["{ar"] = "@return.outer",
                        },
                        goto_next = {
                            [")af"] = "@function.outer",
                            [")if"] = "@function.inner",
                            [")as"] = "@clajs.outer",
                            [")is"] = "@class.inner",
                            [")ac"] = "@conditional.outer",
                            [")ic"] = "@conditional.inner",
                            [")al"] = "@loop.outer",
                            [")il"] = "@loop.inner",
                            [")ap"] = "@parameter.outer",
                            [")ip"] = "@parameter.inner",
                            [")ia"] = "@attribute.inner",
                            [")aa"] = "@attribute.outer",
                            [")ik"] = "@comment.inner",
                            [")ak"] = "@comment.outer",
                            [")ir"] = "@return.inner",
                            [")ar"] = "@return.outer",
                        },
                        goto_previous = {
                            ["(af"] = "@function.outer",
                            ["(if"] = "@function.inner",
                            ["(as"] = "@class.outer",
                            ["(is"] = "@class.inner",
                            ["(ac"] = "@conditional.outer",
                            ["(ic"] = "@conditional.inner",
                            ["(al"] = "@loop.outer",
                            ["(il"] = "@loop.inner",
                            ["(ap"] = "@parameter.outer",
                            ["(ip"] = "@parameter.inner",
                            ["(ia"] = "@attribute.inner",
                            ["(aa"] = "@attribute.outer",
                            ["(ik"] = "@comment.inner",
                            ["(ak"] = "@comment.outer",
                            ["(ir"] = "@return.inner",
                            ["(ar"] = "@return.outer",
                        },
                    },
                    swap = {
                        enable = false,
                        swap_next = {
                            [""] = "@parameter.inner",
                        },
                        swap_previous = {
                            [""] = "@parameter.inner",
                        },
                    },
                },
            })
        end,
    },
    {"wurli/contextindent.nvim", opts = { pattern = "*" }, dependencies = { "nvim-treesitter/nvim-treesitter" },}
}
