return {
  { "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        auto_install = true,
        ensure_installed = {
        },
        highlight = {
          enable = true,
        },
        indent = {
          enable = true,
        },
      })
    end },
  { 'Wansmer/treesj',
    dependencies = { 'nvim-treesitter/nvim-treesitter' },
    config = function()
      require('treesj').setup({
        vim.keymap.set('n', 'ss', require('treesj').toggle),
        vim.keymap.set('n', 'sj', function() require('treesj').toggle({ split = { recursive = true } }) end)
      })
    end, },
  { "nvim-treesitter/nvim-treesitter-textobjects",
    dependencies = {
      "nvim-treesitter/nvim-treesitter",
    },
    config = function()
      require "nvim-treesitter.configs".setup({
        textobjects = {
          select = {
            enable = true,
            include_surrounding_whitespace = false,
            lookahead = true,
            keymaps = {
              ["aj"] = "@call.outer",
              ["ij"] = "@call.inner",
              ["af"] = "@function.outer",
              ["if"] = "@function.inner",
              ["as"] = "@class.outer",
              ["is"] = "@class.inner",
              ["ac"] = "@conditional.outer",
              ["ic"] = "@conditional.inner",
              ["al"] = "@loop.outer",
              ["il"] = "@loop.inner",
              ["ap"] = "@parameter.outer",
              ["ip"] = "@parameter.inner",
              ["ia"] = "@attribute.inner",
              ["aa"] = "@attribute.outer",
              ["ik"] = "@comment.inner",
              ["ak"] = "@comment.outer",
              ["ir"] = "@return.inner",
              ["ar"] = "@return.outer",
            },
            selection_modes = {
              ["@call.outer"] = "V",
              ["@call.inner"] = "v",
              ["@function.outer"] = "V",
              ["@function.inner"] = "v",
              ["@class.outer"] = "V",
              ["@class.inner"] = "v",
              ["@conditional.outer"] = "V",
              ["@conditional.inner"] = "v",
              ["@loop.outer"] = "V",
              ["@loop.inner"] = "v",
              ["@parameter.outer"] = "V",
              ["@parameter.inner"] = "v",
              ["@attribute.outer"] = "V",
              ["@attribute.inner"] = "v",
              ["@comment.inner"] = "v",
              ["@comment.outer"] = "V",
              ["@return.inner"] = "v",
              ["@return.outer"] = "V",
            },
          },
          move = {
            enable = true,
            set_jumps = true,
            goto_next_start = {
              ["]aj"] = "@call.outer",
              ["]ij"] = "@call.inner",
              ["]af"] = "@function.outer",
              ["]if"] = "@function.inner",
              ["]as"] = "@class.outer",
              ["]is"] = "@class.inner",
              ["]ac"] = "@conditional.outer",
              ["]ic"] = "@conditional.inner",
              ["]al"] = "@loop.outer",
              ["]il"] = "@loop.inner",
              ["]ap"] = "@parameter.outer",
              ["]ip"] = "@parameter.inner",
              ["]ia"] = "@attribute.inner",
              ["]aa"] = "@attribute.outer",
              ["]ik"] = "@comment.inner",
              ["]ak"] = "@comment.outer",
              ["]ir"] = "@return.inner",
              ["]ar"] = "@return.outer",
            },
            goto_next_end = {
              ["[aj"] = "@call.outer",
              ["[ij"] = "@call.inner",
              ["[af"] = "@function.outer",
              ["[if"] = "@function.inner",
              ["[as"] = "@class.outer",
              ["[is"] = "@class.inner",
              ["[ac"] = "@conditional.outer",
              ["[ic"] = "@conditional.inner",
              ["[al"] = "@loop.outer",
              ["[il"] = "@loop.inner",
              ["[ap"] = "@parameter.outer",
              ["[ip"] = "@parameter.inner",
              ["[ia"] = "@attribute.inner",
              ["[aa"] = "@attribute.outer",
              ["[ik"] = "@comment.inner",
              ["[ak"] = "@comment.outer",
              ["[ir"] = "@return.inner",
              ["[ar"] = "@return.outer",
            },
            goto_previous_start = {
              ["}aj"] = "@call.outer",
              ["}ij"] = "@call.inner",
              ["}af"] = "@function.outer",
              ["}if"] = "@function.inner",
              ["}as"] = "@class.outer",
              ["}is"] = "@class.inner",
              ["}ac"] = "@conditional.outer",
              ["}ic"] = "@conditional.inner",
              ["}al"] = "@loop.outer",
              ["}il"] = "@loop.inner",
              ["}ap"] = "@parameter.outer",
              ["}ip"] = "@parameter.inner",
              ["}ia"] = "@attribute.inner",
              ["}aa"] = "@attribute.outer",
              ["}ik"] = "@comment.inner",
              ["}ak"] = "@comment.outer",
              ["}ir"] = "@return.inner",
              ["}ar"] = "@return.outer",
            },
            goto_previous_end = {
              ["{aj"] = "@call.outer",
              ["{ij"] = "@call.inner",
              ["{af"] = "@function.outer",
              ["{if"] = "@function.inner",
              ["{as"] = "@class.outer",
              ["{is"] = "@clasj.inner",
              ["{ac"] = "@conditional.outer",
              ["{ic"] = "@conditional.inner",
              ["{al"] = "@loop.outer",
              ["{il"] = "@loop.inner",
              ["{ap"] = "@parameter.outer",
              ["{ip"] = "@parameter.inner",
              ["{ia"] = "@attribute.inner",
              ["{aa"] = "@attribute.outer",
              ["{ik"] = "@comment.inner",
              ["{ak"] = "@comment.outer",
              ["{ir"] = "@return.inner",
              ["{ar"] = "@return.outer",
            },
            goto_next = {
              [")aj"] = "@call.outer",
              [")ij"] = "@call.inner",
              [")af"] = "@function.outer",
              [")if"] = "@function.inner",
              [")as"] = "@clajs.outer",
              [")is"] = "@class.inner",
              [")ac"] = "@conditional.outer",
              [")ic"] = "@conditional.inner",
              [")al"] = "@loop.outer",
              [")il"] = "@loop.inner",
              [")ap"] = "@parameter.outer",
              [")ip"] = "@parameter.inner",
              [")ia"] = "@attribute.inner",
              [")aa"] = "@attribute.outer",
              [")ik"] = "@comment.inner",
              [")ak"] = "@comment.outer",
              [")ir"] = "@return.inner",
              [")ar"] = "@return.outer",
            },
            goto_previous = {
              ["(aj"] = "@call.outer",
              ["(ij"] = "@call.inner",
              ["(af"] = "@function.outer",
              ["(if"] = "@function.inner",
              ["(as"] = "@class.outer",
              ["(is"] = "@class.inner",
              ["(ac"] = "@conditional.outer",
              ["(ic"] = "@conditional.inner",
              ["(al"] = "@loop.outer",
              ["(il"] = "@loop.inner",
              ["(ap"] = "@parameter.outer",
              ["(ip"] = "@parameter.inner",
              ["(ia"] = "@attribute.inner",
              ["(aa"] = "@attribute.outer",
              ["(ik"] = "@comment.inner",
              ["(ak"] = "@comment.outer",
              ["(ir"] = "@return.inner",
              ["(ar"] = "@return.outer",
            },
          },
          swap = {
            enable = false,
            swap_next = {
              [""] = "@parameter.inner",
            },
            swap_previous = {
              [""] = "@parameter.inner",
            },
          },
        },
      })
    end },
}
